# based on https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/android/Dockerfile-base
# we use a gcr.io image and not openjdk:8-jdk-slim because it loads faster in the google Google Cloud Build environment
FROM gcr.io/cloud-builders/javac

ENV DEBIAN_FRONTEND=noninteractive

# make Apt non-interactive
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90builder \
  && echo 'DPkg::Options "--force-confnew";' >> /etc/apt/apt.conf.d/90builder

# Install Dependencies
RUN apt-get update && \
    apt-get install -y \
        git locales sudo openssh-client ca-certificates tar gzip parallel \
        zip unzip bzip2 gnupg curl wget

# Set timezone to UTC by default
RUN ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Use unicode
RUN locale-gen C.UTF-8 || true
ENV LANG=C.UTF-8

# check https://developer.android.com/studio/index.html#command-tools
# commandlinetools-linux-{tools_version}_latest.zip
ARG tools_version=6200805
ARG android_home=/opt/android/sdk
ARG android_compile_sdk_version=29
ARG build_tools_version=29.0.3
ARG ndk_version=android-ndk-r17b
ARG android_ndk_home=/opt/android/${ndk_version}

# Install Android SDK
RUN sudo mkdir -p ${android_home} && \
    curl --silent --show-error --location --fail --retry 3 --output /tmp/${tools_version} https://dl.google.com/android/repository/commandlinetools-linux-${tools_version}_latest.zip && \
    unzip -q /tmp/${tools_version} -d ${android_home} && \
    rm /tmp/${tools_version}

# Set environment variables
ENV ANDROID_HOME ${android_home}
ENV ADB_INSTALL_TIMEOUT 120
ENV PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
ENV ANDROID_COMPILE_SDK ${android_compile_sdk_version}
ENV BUILD_TOOLS ${build_tools_version}

RUN mkdir ~/.android && echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg

# need --sdk_root https://stackoverflow.com/a/60454207
RUN yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses
RUN yes | sdkmanager --sdk_root=${ANDROID_HOME} --update

# Update SDK manager and install system image, platform and build tools
RUN yes | sdkmanager  --sdk_root=${ANDROID_HOME}\
    "tools" \
    "platforms;android-${ANDROID_COMPILE_SDK}" \
    "platform-tools" \
    "extras;android;m2repository" \
    "extras;google;m2repository" \
    "extras;google;google_play_services" \
    "build-tools;${BUILD_TOOLS}"

COPY for_branch /bin
COPY run_build /bin

ENTRYPOINT ["bash", "/bin/run_build"]